### ISSUE TITLE
Вопрос по position.js

### ISSUE THREAD

**Issue by ZzZakko** [MATI-INT/group234#1]
Здравствуйте! 

Прошу разъяснить зачем/почему в данном куске кода присутствует "е":
` $('.scroll_to').click(function(e) {
e.preventDefault();`

2-3 строчка в position.js 

Если я правильно помню\понял, то это отменяет "переход" браузера по ссылке(<a>?)

Также прошу разъяснить этот кусок, после "{":
`$('html').animate({
      'scrollTop': $el.length ? $el.offset().top : 0`

Спасибо.

**Comment by bodrovis** [comment]
`$('.scroll_to').click(function(e) { e.preventDefault();` - отменяет стандартное действие браузера при возникновении данного события. Стандартное событие - переход по ссылке. Так как мы хотим самостоятельно сделать плавный переход, то стандартное действие мы отменяем.

`$('html').animate({ 'scrollTop': $el.length ? $el.offset().top : 0`

* `animate` - анимирует элемент
* `scrollTop` - прокрутка по оси Y
* `$el.length ?` - найден ли элемент (то есть длина массива с найденными элементами отлична от нуля или значения `undefined`)
* `$el.offset().top` - если элемент найден, то взять его положение (смещение) по оси Y относительно верхней границы документа
* `: 0` - если элемент не найден, то просто указать ноль, то есть верх документа. Это нужно в случае, если пользователь нажал по ссылке "наверх" (вот этой https://github.com/MATI-INT/group234/blob/master/position.html#L64)

**Comment by ZzZakko** [comment]
Насчет второго все понятно, спасибо. А насчет первого: для чего именно и почему используется 
'e' ? 
@bodrovis

**Comment by bodrovis** [comment]
`e` - это локальная переменная, которая автоматически передаётся в анонимную функцию, исполняемую при наступлении события. Назвать эту переменную можно как угодно, она в любом случае будет представлять собой объект произошедшего события. Самое простое - вывести её в консоль и посмотреть содержимое. Этот объект указывает, где возникло событие, какие были сопутствующие условия, а также предоставляет ряд методов для манипулирования событием. В частности, метод `preventDefault()` предотвращает стандартное действие, которое выполняет браузер по умолчанию при возникновении данного события.

**Comment by ZzZakko** [comment]
Спасибо! :)
